name: EasyGamemode
version: 1.0.0
api: 4.0.0
author: GamilinoMC
main: Plugin/Main

commands:
   gm1:
     description: Gamemode 1
     permission: test.cmd

permissions:
  test.cmd:
    default: op
    description: GM1 befehl
