name: EasyGamemode
version: 1.0.1
api: 4.0.0
author: GamilinoMC
main: Plugin/Main

commands:
   test:
     description: test
     permission: test.cmd

permissions:
  test.cmd:
    default: op
    description: test befehl
